### ISSUE TITLE
[Bug]: Really bad microphone sound quality

### ISSUE THREAD

**Issue by MEIDUNN** [WiVRn/WiVRn#229]
### Describe the bug

The quality of the microphone (tested on a Quest Pro, which otherwise has a very decent microphone) is significantly lower than it is when ran through Windows. Similar issues can be found in ALVR, but the quality drop is not as significant.

Tested on Fedora 41 using PipeWire (with devel packages), on a Quest Pro using WiVRn provided both solo and via Envision.

Attached below is an audio sample, some pwdump's from ALVR and WiVRN for comparison, and my pw-top information.
I'll attempt to provide more information when required, some of the fields here are kinda hard to fill in when I for instance use Envision as much as I do.

https://github.com/user-attachments/assets/9637e1a8-dbd0-43a0-a456-6d973c1283c9
[pwdump-alvr.txt](https://github.com/user-attachments/files/18292566/pwdump-alvr.txt)
[pwdump-wivrn.txt](https://github.com/user-attachments/files/18292567/pwdump-wivrn.txt)
![image](https://github.com/user-attachments/assets/a658d818-ab4b-4382-b894-e867a3fc27f0)

### Expected behavior

The microphone audio quality to be up to par with the headsets hardware.

### WiVRn Version

0.22 (as well as latest Envision)

### What GPU did the bug occur on?

NVIDIA

### Vulkan Info

WARNING: [Loader Message] Code 0 : Layer VK_LAYER_MND_enable_timeline_semaphore uses API version 1.2 which is older than the application specified API version of 1.3. May cause issues.
ERROR: [Loader Message] Code 0 : libVkLayer_MND_enable_timeline_semaphore.so: cannot open shared object file: No such file or directory
==========
VULKANINFO
==========

Vulkan Instance Version: 1.3.296

Instance Extensions: count = 24
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_headless_surface                : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 8
--------------------------
VK_LAYER_MESA_device_select            Linux device selection layer           1.3.211  version 1
VK_LAYER_MND_enable_timeline_semaphore Monado enable timeline semaphore layer 1.2.199  version 1
VK_LAYER_NV_optimus                    NVIDIA Optimus layer                   1.3.289  version 1
VK_LAYER_OBS_vkcapture_64              OBS Linux game capture                 1.3.290  version 1
VK_LAYER_VALVE_steam_fossilize_32      Steam Pipeline Caching Layer           1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64      Steam Pipeline Caching Layer           1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32        Steam Overlay Layer                    1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64        Steam Overlay Layer                    1.3.207  version 1

Devices:
========
GPU0:
        apiVersion         = 1.3.289
        driverVersion      = 565.77.0.0
        vendorID           = 0x10de
        deviceID           = 0x2204
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = NVIDIA GeForce RTX 3090
        driverID           = DRIVER_ID_NVIDIA_PROPRIETARY
        driverName         = NVIDIA
        driverInfo         = 565.77
        conformanceVersion = 1.3.8.2
        deviceUUID         = 1f3a1b71-fba9-94ab-5a0f-1461b2193c12
        driverUUID         = 5d948742-de2b-5e32-9692-c2a5621aed9a
GPU1:
        apiVersion         = 1.3.289
        driverVersion      = 0.0.1
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 19.1.0, 256 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 24.2.8 (LLVM 19.1.0)
        conformanceVersion = 1.3.1.1
        deviceUUID         = 6d657361-3234-2e32-2e38-000000000000
        driverUUID         = 6c6c766d-7069-7065-5555-494400000000

### What HMD did the bug occur on?

Quest Pro

**Comment by xytovl** [comment]
Can you provide logs from `adb logcat` when you start the connection. It should print information about the available audio devices on headset.

**Comment by MEIDUNN** [comment]
> Can you provide logs from `adb logcat` when you start the connection. It should print information about the available audio devices on headset.

`adb logcat` gives me nothing, just sits on "waiting for device".

**Comment by xytovl** [comment]
Branch https://github.com/WiVRn/WiVRn/tree/fix/mic-48kHz should fix the issue, please test with apk from https://github.com/WiVRn/WiVRn/actions/workflows/Build.yml?query=branch%3Afix%2Fmic-48kHz and matching server build, you can use the flatpak from the same CI run.

**Comment by MEIDUNN** [comment]
Appears I still have the same issue, unfortunately. 

https://github.com/user-attachments/assets/3bb52499-577d-4011-88c1-449ee903a9f3
Just to verify, I'm using the build results here; https://github.com/WiVRn/WiVRn/actions/runs/12618544673
namely the apk-Standard-Debug and the wivrn-server-x86_64. Hoping I didn't misunderstand the instructions.

**Comment by xytovl** [comment]
That's the correct link (Release build will have better performance, but won't affect the current issue), make sure you are running the right build as it will install with a different identifier (org.meumeu.wivrn.testing). You can verify in the about tab that version shows something-g510764c.

If the version you are running is correct and issue persists, I will need client logs to further investigate. You may fix the adb logcat stuck at "waiting for device" by replugging the headset, make sure to have usb debugging enabled in Quest settings and allow the connection.

**Comment by xytovl** [comment]
Microphone now defaults to 48kHz with f3d2c6ffe4da3cc8bb7df6ef28c62b8d959f0463

**Comment by MEIDUNN** [comment]
@xytovl Hi there!

Sorry for the very late reply here, it seems I had email notifications off and I never saw the new instructions. I also had to swap away from Linux for a few months, so I simply never checked back into the thread. However, I'm now running Arch and find myself still having the same issues, even after the new "Unprocessed Microphone Audio" setting, which does no discernible difference.

One piece of info I notice I neglected to add: All of these issues are on **wireless**, which explains why **adb catlog** gave no output - the headset is **NOT** connected via cable.

When I do use adb-catlog (over cable), I get a slew of continues messages that don't seem to be of much help at all, but I'll attach it here anyway. I'm also unable to connect the headset via WiVRn, as I get a "Socket Shutdown" error.

[adb-catlog.txt](https://github.com/user-attachments/files/20007401/adb-catlog.txt)

**So, to reiterate:**
The low microphone quality appears on Wireless WiVRn, on a WiFi 6e router (two different routers tested), at 50-100mbps transfer rates, with or without "Unprocessed Microphone Audio" selected in settings, in both VR applications and in recording software outside of VR that use the headset microphone. I'm unable to test this over a wired connection.

**The issue is not completed or resolved**, so I'll keep an eye on here proper now (With email notifications on) to help further.

**Comment by xytovl** [comment]
The attached logs do not show the whole session, but only when in the lobby.
Please start the `adb logcat` command, reproduce the issue, then stop the command and post the associated logs.

**Comment by MEIDUNN** [comment]
The problem is that I can’t. That log is a snippet of what it is continuously, forever looping. It does nt stop, and I can’t stop it unless I unplug the headset. I’m also unable to connect to a session, as I get a “Socket Shutdown” error.

**Comment by xytovl** [comment]
Just run `adb logcat > ~/log.txt` to stream the data to a file, which will contain the full output. The stop the process with Ctrl + C when you are done collecting data.

**Comment by MEIDUNN** [comment]
[log.txt](https://github.com/user-attachments/files/20011695/log.txt)

Alright, here you go. This is:
1. Running the command
2. Connecting the headset via cable
3. Letting it sit for a few seconds
4. Hitting Ctrl + C

It's bout 33,000 lines of logs, much of which is in the first sample I sent, so hopefully the first opening lines are of any help.

**Comment by MEIDUNN** [comment]
That's because, as I stated twice before, the headset doesn't connect to the server. I get a "Socket Shutdown" error when attempting.

I attempted a WiFi connection again, and while sitting on "start a VR application" tested the microphone. The issue remains there too.

**Comment by xytovl** [comment]
There shouldn't be a difference if cable is connected or not, do not use wired mode (in general don't use it, it doesn't have any benefit over wireless unless there's too many wireless devices).
Do not start the client through envision, just through normal headset UI.

**Comment by MEIDUNN** [comment]
Well that's the issue - when I connect wirelessly, adb logcat does nothing.

The process is this:
1. I start the Wireless server through Envision
2. I connect to it via the HMD Client (wirelessly) - successfully
3. I run "adb logcat"
4. It stops at "- waiting for device -"
