### ISSUE TITLE
[Bug]: 32bit Build Broken (v0.23.2)

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#271]
### Describe the bug

32bit is failing to build again.

### Steps to Reproduce

1. Build
2. Build errors

```
FAILED: common/CMakeFiles/wivrn-common.dir/vk/error_category.cpp.o 
/usr/bin/g++ -DVULKAN_HPP_NO_STRUCT_CONSTRUCTORS -I/builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/redhat-linux-build/common/wivrn-common_autogen/include -I/builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common -I/builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/redhat-linux-build/common -isystem /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/external -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcoroutines -O2 -g -DNDEBUG -std=gnu++23 -flto=auto -fno-fat-lto-objects -fPIC -fdiagnostics-color -Wall -Wextra -pedantic -Wundef -Wno-missing-field-initializers -Wno-unused-parameter -Wno-comment -Wno-unused-variable -Wno-sign-compare -Wno-volatile -Wno-array-bounds -MD -MT common/CMakeFiles/wivrn-common.dir/vk/error_category.cpp.o -MF common/CMakeFiles/wivrn-common.dir/vk/error_category.cpp.o.d -o common/CMakeFiles/wivrn-common.dir/vk/error_category.cpp.o -c /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common/vk/error_category.cpp
In file included from /usr/include/vulkan/vulkan.hpp:8864,
                 from /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common/vk/error_category.cpp:22:
/usr/include/vulkan/vulkan_structs.hpp: In member function ‘bool vk::PipelineShaderStageCreateInfo::operator==(const vk::PipelineShaderStageCreateInfo&) const’:
/usr/include/vulkan/vulkan_structs.hpp:16478:127: error: no match for ‘operator==’ (operand types are ‘const vk::ShaderModule’ and ‘const vk::ShaderModule’)
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                        ~~~~~~ ^~ ~~~~~~~~~~
      |                                                                                                                        |             |
      |                                                                                                                        |             const vk::ShaderModule
      |                                                                                                                        const vk::ShaderModule
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: there are 8 candidates
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                        ~~~~~~~^~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 1: ‘operator==(int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 2: ‘operator==(int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 3: ‘operator==(long long unsigned int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 4: ‘operator==(long long unsigned int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan.hpp:203:8: note: candidate 5: ‘template<unsigned int N, unsigned int M> bool vk::operator==(const ArrayWrapper1D<char, N>&, const ArrayWrapper1D<char, M>&)’
  203 |   bool operator==( ArrayWrapper1D<char, N> const & lhs, ArrayWrapper1D<char, M> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:203:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:134: note:   ‘const vk::ShaderModule’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                                      ^~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: candidate 6: ‘template<unsigned int N> bool vk::operator==(const std::string&, const ArrayWrapper1D<char, N>&)’
  248 |   bool operator==( std::string const & lhs, ArrayWrapper1D<char, N> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:134: note:   ‘const vk::ShaderModule’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                                      ^~~~~~
In file included from /usr/include/vulkan/vulkan.hpp:8863:
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: candidate 7: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(const T&, std::nullptr_t)’
17737 |   bool operator==( T const & v, std::nullptr_t )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:134: note:   cannot convert ‘rhs.vk::PipelineShaderStageCreateInfo::module’ (type ‘const vk::ShaderModule’) to type ‘std::nullptr_t’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                                  ~~~~^~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: candidate 8: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(std::nullptr_t, const T&)’
17743 |   bool operator==( std::nullptr_t, T const & v )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:120: note:   cannot convert ‘((const vk::PipelineShaderStageCreateInfo*)this)->vk::PipelineShaderStageCreateInfo::module’ (type ‘const vk::ShaderModule’) to type ‘std::nullptr_t’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                        ^~~~~~
/usr/include/vulkan/vulkan_structs.hpp: In member function ‘bool vk::CuFunctionCreateInfoNVX::operator==(const vk::CuFunctionCreateInfoNVX&) const’:
/usr/include/vulkan/vulkan_structs.hpp:20196:75: error: no match for ‘operator==’ (operand types are ‘const vk::CuModuleNVX’ and ‘const vk::CuModuleNVX’)
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                    ~~~~~~ ^~ ~~~~~~~~~~
      |                                                                    |             |
      |                                                                    |             const vk::CuModuleNVX
      |                                                                    const vk::CuModuleNVX
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: there are 8 candidates
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                    ~~~~~~~^~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 1: ‘operator==(int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 2: ‘operator==(int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 3: ‘operator==(long long unsigned int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 4: ‘operator==(long long unsigned int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan.hpp:203:8: note: candidate 5: ‘template<unsigned int N, unsigned int M> bool vk::operator==(const ArrayWrapper1D<char, N>&, const ArrayWrapper1D<char, M>&)’
  203 |   bool operator==( ArrayWrapper1D<char, N> const & lhs, ArrayWrapper1D<char, M> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:203:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:82: note:   ‘const vk::CuModuleNVX’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                                  ^~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: candidate 6: ‘template<unsigned int N> bool vk::operator==(const std::string&, const ArrayWrapper1D<char, N>&)’
  248 |   bool operator==( std::string const & lhs, ArrayWrapper1D<char, N> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:82: note:   ‘const vk::CuModuleNVX’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                                  ^~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: candidate 7: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(const T&, std::nullptr_t)’
17737 |   bool operator==( T const & v, std::nullptr_t )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:82: note:   cannot convert ‘rhs.vk::CuFunctionCreateInfoNVX::module’ (type ‘const vk::CuModuleNVX’) to type ‘std::nullptr_t’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                              ~~~~^~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: candidate 8: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(std::nullptr_t, const T&)’
17743 |   bool operator==( std::nullptr_t, T const & v )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:68: note:   cannot convert ‘((const vk::CuFunctionCreateInfoNVX*)this)->vk::CuFunctionCreateInfoNVX::module’ (type ‘const vk::CuModuleNVX’) to type ‘std::nullptr_t’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                    ^~~~~~
/usr/include/vulkan/vulkan_structs.hpp: In member function ‘bool vk::DisplayPropertiesKHR::operator==(const vk::DisplayPropertiesKHR&) const’:
/usr/include/vulkan/vulkan_structs.hpp:33526:24: error: no match for ‘operator==’ (operand types are ‘const vk::DisplayKHR’ and ‘const vk::DisplayKHR’)
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                ~~~~~~~ ^~ ~~~~~~~~~~~
      |                |              |
      |                |              const vk::DisplayKHR
      |                const vk::DisplayKHR
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: there are 8 candidates
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                ~~~~~~~~^~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 1: ‘operator==(int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 2: ‘operator==(int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 3: ‘operator==(long long unsigned int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 4: ‘operator==(long long unsigned int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan.hpp:203:8: note: candidate 5: ‘template<unsigned int N, unsigned int M> bool vk::operator==(const ArrayWrapper1D<char, N>&, const ArrayWrapper1D<char, M>&)’
  203 |   bool operator==( ArrayWrapper1D<char, N> const & lhs, ArrayWrapper1D<char, M> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:203:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:31: note:   ‘const vk::DisplayKHR’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                               ^~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: candidate 6: ‘template<unsigned int N> bool vk::operator==(const std::string&, const ArrayWrapper1D<char, N>&)’
  248 |   bool operator==( std::string const & lhs, ArrayWrapper1D<char, N> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:31: note:   ‘const vk::DisplayKHR’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                               ^~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: candidate 7: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(const T&, std::nullptr_t)’
17737 |   bool operator==( T const & v, std::nullptr_t )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:31: note:   cannot convert ‘rhs.vk::DisplayPropertiesKHR::display’ (type ‘const vk::DisplayKHR’) to type ‘std::nullptr_t’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                           ~~~~^~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: candidate 8: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(std::nullptr_t, const T&)’
17743 |   bool operator==( std::nullptr_t, T const & v )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:16: note:   cannot convert ‘((const vk::DisplayPropertiesKHR*)this)->vk::DisplayPropertiesKHR::display’ (type ‘const vk::DisplayKHR’) to type ‘std::nullptr_t’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                ^~~~~~~
```

```
FAILED: common/CMakeFiles/wivrn-common.dir/vk/allocation.cpp.o 
/usr/bin/g++ -DVULKAN_HPP_NO_STRUCT_CONSTRUCTORS -I/builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/redhat-linux-build/common/wivrn-common_autogen/include -I/builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common -I/builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/redhat-linux-build/common -isystem /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/external -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcoroutines -O2 -g -DNDEBUG -std=gnu++23 -flto=auto -fno-fat-lto-objects -fPIC -fdiagnostics-color -Wall -Wextra -pedantic -Wundef -Wno-missing-field-initializers -Wno-unused-parameter -Wno-comment -Wno-unused-variable -Wno-sign-compare -Wno-volatile -Wno-array-bounds -MD -MT common/CMakeFiles/wivrn-common.dir/vk/allocation.cpp.o -MF common/CMakeFiles/wivrn-common.dir/vk/allocation.cpp.o.d -o common/CMakeFiles/wivrn-common.dir/vk/allocation.cpp.o -c /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common/vk/allocation.cpp
In file included from /usr/include/vulkan/vulkan.hpp:8864,
                 from /usr/include/vulkan/vulkan_raii.hpp:11,
                 from /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common/vk/allocation.h:25,
                 from /builddir/build/BUILD/wivrn-0.23.2-build/WiVRn-0.23.2/common/vk/allocation.cpp:20:
/usr/include/vulkan/vulkan_structs.hpp: In member function ‘bool vk::PipelineShaderStageCreateInfo::operator==(const vk::PipelineShaderStageCreateInfo&) const’:
/usr/include/vulkan/vulkan_structs.hpp:16478:127: error: no match for ‘operator==’ (operand types are ‘const vk::ShaderModule’ and ‘const vk::ShaderModule’)
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                        ~~~~~~ ^~ ~~~~~~~~~~
      |                                                                                                                        |             |
      |                                                                                                                        |             const vk::ShaderModule
      |                                                                                                                        const vk::ShaderModule
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: there are 8 candidates
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                        ~~~~~~~^~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 1: ‘operator==(int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 2: ‘operator==(int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 3: ‘operator==(long long unsigned int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: candidate 4: ‘operator==(long long unsigned int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:16478:127: note: no known conversion for argument 2 from ‘const vk::ShaderModule’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan.hpp:203:8: note: candidate 5: ‘template<unsigned int N, unsigned int M> bool vk::operator==(const ArrayWrapper1D<char, N>&, const ArrayWrapper1D<char, M>&)’
  203 |   bool operator==( ArrayWrapper1D<char, N> const & lhs, ArrayWrapper1D<char, M> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:203:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:134: note:   ‘const vk::ShaderModule’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                                      ^~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: candidate 6: ‘template<unsigned int N> bool vk::operator==(const std::string&, const ArrayWrapper1D<char, N>&)’
  248 |   bool operator==( std::string const & lhs, ArrayWrapper1D<char, N> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:134: note:   ‘const vk::ShaderModule’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                                      ^~~~~~
In file included from /usr/include/vulkan/vulkan.hpp:8863:
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: candidate 7: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(const T&, std::nullptr_t)’
17737 |   bool operator==( T const & v, std::nullptr_t )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:134: note:   cannot convert ‘rhs.vk::PipelineShaderStageCreateInfo::module’ (type ‘const vk::ShaderModule’) to type ‘std::nullptr_t’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                                  ~~~~^~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: candidate 8: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(std::nullptr_t, const T&)’
17743 |   bool operator==( std::nullptr_t, T const & v )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:16478:120: note:   cannot convert ‘((const vk::PipelineShaderStageCreateInfo*)this)->vk::PipelineShaderStageCreateInfo::module’ (type ‘const vk::ShaderModule’) to type ‘std::nullptr_t’
16478 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( flags == rhs.flags ) && ( stage == rhs.stage ) && ( module == rhs.module ) &&
      |                                                                                                                        ^~~~~~
/usr/include/vulkan/vulkan_structs.hpp: In member function ‘bool vk::CuFunctionCreateInfoNVX::operator==(const vk::CuFunctionCreateInfoNVX&) const’:
/usr/include/vulkan/vulkan_structs.hpp:20196:75: error: no match for ‘operator==’ (operand types are ‘const vk::CuModuleNVX’ and ‘const vk::CuModuleNVX’)
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                    ~~~~~~ ^~ ~~~~~~~~~~
      |                                                                    |             |
      |                                                                    |             const vk::CuModuleNVX
      |                                                                    const vk::CuModuleNVX
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: there are 8 candidates
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                    ~~~~~~~^~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 1: ‘operator==(int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 2: ‘operator==(int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 3: ‘operator==(long long unsigned int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: candidate 4: ‘operator==(long long unsigned int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:20196:75: note: no known conversion for argument 2 from ‘const vk::CuModuleNVX’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan.hpp:203:8: note: candidate 5: ‘template<unsigned int N, unsigned int M> bool vk::operator==(const ArrayWrapper1D<char, N>&, const ArrayWrapper1D<char, M>&)’
  203 |   bool operator==( ArrayWrapper1D<char, N> const & lhs, ArrayWrapper1D<char, M> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:203:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:82: note:   ‘const vk::CuModuleNVX’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                                  ^~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: candidate 6: ‘template<unsigned int N> bool vk::operator==(const std::string&, const ArrayWrapper1D<char, N>&)’
  248 |   bool operator==( std::string const & lhs, ArrayWrapper1D<char, N> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:82: note:   ‘const vk::CuModuleNVX’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                                  ^~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: candidate 7: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(const T&, std::nullptr_t)’
17737 |   bool operator==( T const & v, std::nullptr_t )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:82: note:   cannot convert ‘rhs.vk::CuFunctionCreateInfoNVX::module’ (type ‘const vk::CuModuleNVX’) to type ‘std::nullptr_t’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                              ~~~~^~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: candidate 8: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(std::nullptr_t, const T&)’
17743 |   bool operator==( std::nullptr_t, T const & v )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:20196:68: note:   cannot convert ‘((const vk::CuFunctionCreateInfoNVX*)this)->vk::CuFunctionCreateInfoNVX::module’ (type ‘const vk::CuModuleNVX’) to type ‘std::nullptr_t’
20196 |       return ( sType == rhs.sType ) && ( pNext == rhs.pNext ) && ( module == rhs.module ) && ( ( pName == rhs.pName ) || ( strcmp( pName, rhs.pName ) == 0 ) );
      |                                                                    ^~~~~~
/usr/include/vulkan/vulkan_structs.hpp: In member function ‘bool vk::DisplayPropertiesKHR::operator==(const vk::DisplayPropertiesKHR&) const’:
/usr/include/vulkan/vulkan_structs.hpp:33526:24: error: no match for ‘operator==’ (operand types are ‘const vk::DisplayKHR’ and ‘const vk::DisplayKHR’)
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                ~~~~~~~ ^~ ~~~~~~~~~~~
      |                |              |
      |                |              const vk::DisplayKHR
      |                const vk::DisplayKHR
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: there are 8 candidates
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                ~~~~~~~~^~~~~~~~~~~~~~
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 1: ‘operator==(int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 2: ‘operator==(int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 3: ‘operator==(long long unsigned int, int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘int’
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: candidate 4: ‘operator==(long long unsigned int, long long unsigned int)’ (built-in)
/usr/include/vulkan/vulkan_structs.hpp:33526:24: note: no known conversion for argument 2 from ‘const vk::DisplayKHR’ to ‘long long unsigned int’
/usr/include/vulkan/vulkan.hpp:203:8: note: candidate 5: ‘template<unsigned int N, unsigned int M> bool vk::operator==(const ArrayWrapper1D<char, N>&, const ArrayWrapper1D<char, M>&)’
  203 |   bool operator==( ArrayWrapper1D<char, N> const & lhs, ArrayWrapper1D<char, M> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:203:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:31: note:   ‘const vk::DisplayKHR’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                               ^~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: candidate 6: ‘template<unsigned int N> bool vk::operator==(const std::string&, const ArrayWrapper1D<char, N>&)’
  248 |   bool operator==( std::string const & lhs, ArrayWrapper1D<char, N> const & rhs ) VULKAN_HPP_NOEXCEPT
      |        ^~~~~~~~
/usr/include/vulkan/vulkan.hpp:248:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:31: note:   ‘const vk::DisplayKHR’ is not derived from ‘const vk::ArrayWrapper1D<char, N>’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                               ^~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: candidate 7: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(const T&, std::nullptr_t)’
17737 |   bool operator==( T const & v, std::nullptr_t )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17737:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:31: note:   cannot convert ‘rhs.vk::DisplayPropertiesKHR::display’ (type ‘const vk::DisplayKHR’) to type ‘std::nullptr_t’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                           ~~~~^~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: candidate 8: ‘template<class T, typename std::enable_if<vk::isVulkanHandleType<Type>::value, int>::type <anonymous> > bool vk::operator==(std::nullptr_t, const T&)’
17743 |   bool operator==( std::nullptr_t, T const & v )
      |        ^~~~~~~~
/usr/include/vulkan/vulkan_handles.hpp:17743:8: note: template argument deduction/substitution failed:
/usr/include/vulkan/vulkan_structs.hpp:33526:16: note:   cannot convert ‘((const vk::DisplayPropertiesKHR*)this)->vk::DisplayPropertiesKHR::display’ (type ‘const vk::DisplayKHR’) to type ‘std::nullptr_t’
33526 |       return ( display == rhs.display ) && ( ( displayName == rhs.displayName ) || ( strcmp( displayName, rhs.displayName ) == 0 ) ) &&
      |                ^~~~~~~
```

### Expected behavior

Clean build

### WiVRn Version

v0.23.2

### What GPU did the bug occur on?

Other

### What HMD did the bug occur on?

Other

**Comment by Meumeu** [comment]
It's fixed in https://github.com/KhronosGroup/Vulkan-Hpp/pull/2013, in Vulkan-HPP 1.4.304

**Comment by damaestro** [comment]
Huh.. interesting. I was building against 1.4.304 so maybe it's still broken.

**Comment by damaestro** [comment]
As a note, we disabled building 32bit in the Fedora package.
