### ISSUE TITLE
Server Goes Into Bad State When Client Disconnects

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#54]
When a client disconnects without starting video the server goes into a bad state and is no longer able to be connected to.

```
ERROR [run] Exception in network thread: Socket shutdown
```

Reproduction steps:

* Start the server
* Connect the HMD client to the server without an OpenXR application running, the client enters the "waiting for video" state

To trigger the bug do either of the following:

* Click "cancel" on the client
* Close the HMD app through the android platform

**Comment by xytovl** [comment]
This should be fixed in dev since reconnection support, can you verify?

**Comment by damaestro** [comment]
Seems this is still an issue using the same reproduction steps. The client shows waiting for connection until the server is restarted or the timeout is hit. Starting an application doesn't bring it back either:

```
ERROR [run] Exception in network thread: Socket shutdown
 INFO [client_loop] Client 1 connected
 INFO [ipc_handle_instance_describe_client] Client info:
	id: 1
	application_name: 'OpenComposite_hlvr'
	pid: 14783
	extensions:
		ext_hand_tracking_enabled: true
		ext_eye_gaze_interaction_enabled: false
		ext_hand_interaction_enabled: false
```

**Comment by damaestro** [comment]
On the HMD side all I get is:

```
06-27 19:59:14.259 12535 12570 E WiVRn   : [2024-06-27 19:59:14.259] [WiVRn] [error] Error connecting to server: Cannot connect to davr (192.168....): No handshake received
06-27 19:59:14.259 12535 12570 E WiVRn   : Cannot connect to davr (fe80::...): Network is unreachable
```

**Comment by PassiveLemon** [comment]
I've encountered a similar problem. I kill Wlx-Overlay-S to exit the VR session and I am unable to reconnect back to the server, restarting the systemd service is the only fix.

This might also be a factor in why my WiVRn audio source and sink stay open when all clients disconnect, but I can open that in a different issue.

**Comment by damaestro** [comment]
This is still valid, tested on https://github.com/WiVRn/WiVRn/commit/c6aa376968e0bfe15983e2d696239fa10506eae1 and still can reproduce.

**Comment by damaestro** [comment]
This is still valid, tested on https://github.com/WiVRn/WiVRn/commit/dbe6c21e6d74682fc3d0a5dbcc728d99c4e8a2bd and still can reproduce.

However, if an openxr application is running the issue does not present itself. I'm able to close the HMD side in any way I see fit and things appear to keep working.
